package com.goovat.phoneguardian.evidence

enum class SecurityEventType {
    OWNER_VERIFICATION_FAILED,
    OWNER_VERIFICATION_SUCCEEDED,
    DEVICE_PICKUP,
    MOTION_DETECTED,
    CHARGER_CONNECTED,
    CHARGER_DISCONNECTED,
    USB_CONNECTED,
    SIM_CHANGED,
    NETWORK_CHANGED,
    DEVICE_REBOOTED,
    LOCATION_UPDATED,
    THEFT_MODE_ACTIVATED,
    THEFT_MODE_DEACTIVATED,
    REMOTE_COMMAND_RECEIVED,
    REMOTE_COMMAND_EXECUTED
}
